import Link from "next/link";

export const metadata = {
  title: "Dr. Maya Reynolds, PsyD | Anxiety & Trauma Therapist in Santa Monica",
  description: "Dr. Maya Reynolds offers anxiety, trauma, burnout, CBT, EMDR, and telehealth therapy for adults in Santa Monica and California.",
};

const services = [
  ["01", "Anxiety & Panic Therapy", "Support for constant worry, panic, overthinking, body tension, and sleep difficulties, using practical tools to help you feel calmer in daily life."],
  ["02", "Trauma & EMDR Therapy", "Carefully paced work for single-incident trauma and long-standing patterns connected to childhood, relationships, or chronic stress."],
  ["03", "Burnout & Perfectionism", "Therapy for professionals, entrepreneurs, and creatives who feel disconnected from themselves after years of pushing through pressure."],
];

export default function DrMayaReynoldsPage() {
  return <main className="min-h-screen bg-[#f8f5ef] text-[#183a3a]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><Link href="/" className="font-serif text-2xl font-semibold">Harbor Mind</Link><Link href="/" className="text-sm font-semibold">← Back to home</Link></nav>
    <section className="mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-10 lg:grid-cols-[1.1fr_.9fr] lg:px-10"><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c96d5c]">Santa Monica • California Telehealth</p><h1 className="mt-5 font-serif text-5xl leading-[1.04] sm:text-6xl">Anxiety and trauma therapy for adults ready to feel more like themselves.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#476260]">Dr. Maya Reynolds, PsyD, offers warm, collaborative therapy for adults feeling overwhelmed by anxiety, panic, burnout, perfectionism, or the lasting impact of past experiences.</p><a href="#contact" className="mt-9 w-fit rounded-full bg-[#c96d5c] px-7 py-4 font-semibold text-white">Begin with a consultation</a></div><div className="relative"><div className="absolute -inset-4 rounded-[3rem] bg-[#dceae4]"/><img src="/images/maya-000.png" alt="Dr. Maya Reynolds, PsyD" className="relative h-[555px] w-full rounded-[2.5rem] object-cover object-top shadow-xl"/></div></section>
    <section className="bg-[#183a3a] px-6 py-24 text-white lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f2b4a7]">Meet Dr. Maya Reynolds</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Practical tools. Lasting insight.</h2></div><div className="space-y-5 text-lg leading-8 text-[#dceae4]"><p>Dr. Reynolds is a licensed clinical psychologist based in Santa Monica, California. She works with thoughtful, high-achieving adults who look functional on the outside while privately feeling exhausted, stuck, or emotionally on edge.</p><p>Her work integrates cognitive-behavioral therapy, EMDR, mindfulness-based practices, and body-oriented techniques to address both the emotional and physiological sides of anxiety, trauma, and chronic stress.</p><p>Her goal is not only symptom relief, but deeper insight, resilience, and a stronger relationship with yourself over time.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c96d5c]">Areas of support</p><h2 className="mt-4 max-w-2xl font-serif text-4xl sm:text-5xl">Support for what feels heavy beneath the surface.</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{services.map(([number,title,text])=><article key={number} className="rounded-[2rem] border border-[#d7e2db] bg-white p-8"><p className="font-bold text-[#c96d5c]">{number}</p><h3 className="mt-8 font-serif text-3xl">{title}</h3><p className="mt-5 leading-7 text-[#476260]">{text}</p></article>)}</div></section>
    <section className="bg-[#dceae4] px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div className="grid grid-cols-2 gap-4"><img src="/images/maya-001.jpg" alt="Dr. Reynolds' therapy office" className="mt-10 h-72 w-full rounded-[2rem] object-cover"/><img src="/images/maya-002.jpg" alt="Private Santa Monica therapy office" className="h-72 w-full rounded-[2rem] object-cover"/></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c96d5c]">A calm place to begin</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">In-person therapy in Santa Monica.</h2><p className="mt-6 text-lg leading-8 text-[#476260]">A quiet, private space with natural light and an uncluttered environment, designed to help you feel more at ease when you arrive.</p><p className="mt-6 font-semibold">123th Street 45 W, Santa Monica, CA 90401</p></div></div></section>
    <section id="contact" className="mx-6 my-6 rounded-[2.5rem] bg-[#c96d5c] px-7 py-20 text-center text-white lg:mx-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#fde2dc]">Start here</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-4xl sm:text-5xl">You do not have to keep pushing through alone.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#fde2dc]">Request a consultation for anxiety, trauma, or burnout therapy in Santa Monica or through secure California telehealth.</p><a href="mailto:hello@drmayareynolds.com" className="mt-8 inline-block rounded-full bg-white px-7 py-4 font-semibold text-[#183a3a]">Request a consultation</a></section>
  </main>;
}
